project_id = "ipdzkzlrcyrcfwvhiulc"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.verify-session]
verify_jwt = false
